# -*- coding: utf-8 -*-
"""Te damos la bienvenida a Colaboratory

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/notebooks/intro.ipynb
"""

#Actividad en clases

import itertools
import time
import matplotlib.pyplot as plt


Contraseña = input("Ingresa la contraseña máximo 4 letras: ")
Alfabeto = "abcdefghijklmnopqrstuvwxyz"
Intentos = 0
Inicio = time.time()
Encontrada = False

longitudes = []
intentos_lista = []

for i in range(1, len(Contraseña) + 1):
    for combinacion in itertools.product(Alfabeto, repeat=i):
        Intentos += 1
        intento = "".join(combinacion)

        if intento == Contraseña:
            print("Contraseña encontrada felicidades :", Contraseña)
            final = time.time()
            print("Intentos realizados:", Intentos)
            print("Tiempo:", round(final - Inicio, 4), "segundos")
            Encontrada = True
            break


    longitudes.append(i)
    intentos_lista.append(Intentos)

    if Encontrada:
        break


plt.plot(longitudes, intentos_lista, marker='o')
plt.title("Fuerza bruta vs longitud de contraseña")
plt.xlabel("Longitud de la contraseña")
plt.ylabel("Número de intentos")
plt.grid()

plt.show()